// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/control.proto

// The control plane mirrors SIP's INVITE/BYE semantics without a SIP stack.
// StartCall negotiates the media parameters and returns a call ID and the port
// to send RTP to; EndCall tears the call down and exchanges each side's view of
// what happened.
//
// It exists because four things are impossible to get right from the media
// stream alone:
//
//  1. Packet loss at the edges of a stream. A receiver reconstructs loss from
//     gaps between sequence numbers that arrived, so it cannot detect loss at
//     either end: nothing later reveals a trailing gap, and nothing earlier
//     anchors a leading one — a receiver whose first packet was dropped simply
//     starts counting one packet in. EndCall carries both ends of the range
//     the sender emitted, which closes the blind spot. Real endpoints learn
//     the same range from RTCP.
//
//  2. Knowing when a call ended. Without a teardown message the gateway has to
//     infer the end from silence, which means it keeps filling playout slots
//     with concealment for as long as its hangover window lasts, inflating the
//     conceal rate of every call.
//
//  3. The return media path. The gateway synthesizes audio but has nowhere to
//     send it until the caller says where to listen.
//
//  4. The client's network impairment profile. Nothing in an RTP stream says
//     how it was degraded, so the gateway cannot otherwise label a call with
//     the conditions it was sent under.

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Codec is the G.711 variant for a call.
type Codec int32

const (
	Codec_CODEC_UNSPECIFIED Codec = 0
	Codec_CODEC_PCMU        Codec = 1 // G.711 u-law, RTP payload type 0
	Codec_CODEC_PCMA        Codec = 2 // G.711 A-law, RTP payload type 8
)

// Enum value maps for Codec.
var (
	Codec_name = map[int32]string{
		0: "CODEC_UNSPECIFIED",
		1: "CODEC_PCMU",
		2: "CODEC_PCMA",
	}
	Codec_value = map[string]int32{
		"CODEC_UNSPECIFIED": 0,
		"CODEC_PCMU":        1,
		"CODEC_PCMA":        2,
	}
)

func (x Codec) Enum() *Codec {
	p := new(Codec)
	*p = x
	return p
}

func (x Codec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Codec) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_proto_enumTypes[0].Descriptor()
}

func (Codec) Type() protoreflect.EnumType {
	return &file_proto_control_proto_enumTypes[0]
}

func (x Codec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Codec.Descriptor instead.
func (Codec) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

type StartCallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller and callee identifiers. Free-form; they appear in the call log and
	// on the trace, as a SIP From/To would.
	From  string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To    string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Codec Codec  `protobuf:"varint,3,opt,name=codec,proto3,enum=voicedemo.control.v1.Codec" json:"codec,omitempty"`
	// The synchronization source the client will use on its RTP stream. This is
	// what binds the signaled call to the media that follows, the way SDP binds
	// a session to its RTP.
	Ssrc uint32 `protobuf:"varint,4,opt,name=ssrc,proto3" json:"ssrc,omitempty"`
	// Where to send synthesized audio back. The gateway combines this port with
	// the source address it observes on the inbound RTP, which is what makes the
	// return path work from behind NAT. Zero means the client is not listening
	// and the gateway should not send audio back.
	ReturnPort uint32 `protobuf:"varint,5,opt,name=return_port,json=returnPort,proto3" json:"return_port,omitempty"`
	// The network impairment profile the client is applying to its own outbound
	// stream. The gateway cannot discover this from the media, so the client has
	// to declare it for the call to be labeled honestly.
	NetworkProfile string `protobuf:"bytes,6,opt,name=network_profile,json=networkProfile,proto3" json:"network_profile,omitempty"`
	// Packetization interval. Only 20 ms is supported; the field exists so a
	// mismatch is rejected explicitly rather than producing silently wrong
	// timestamp arithmetic.
	PtimeMs       uint32 `protobuf:"varint,7,opt,name=ptime_ms,json=ptimeMs,proto3" json:"ptime_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCallRequest) Reset() {
	*x = StartCallRequest{}
	mi := &file_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCallRequest) ProtoMessage() {}

func (x *StartCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCallRequest.ProtoReflect.Descriptor instead.
func (*StartCallRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *StartCallRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *StartCallRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *StartCallRequest) GetCodec() Codec {
	if x != nil {
		return x.Codec
	}
	return Codec_CODEC_UNSPECIFIED
}

func (x *StartCallRequest) GetSsrc() uint32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

func (x *StartCallRequest) GetReturnPort() uint32 {
	if x != nil {
		return x.ReturnPort
	}
	return 0
}

func (x *StartCallRequest) GetNetworkProfile() string {
	if x != nil {
		return x.NetworkProfile
	}
	return ""
}

func (x *StartCallRequest) GetPtimeMs() uint32 {
	if x != nil {
		return x.PtimeMs
	}
	return 0
}

type StartCallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The gateway's identifier for the call. It is the Agent Observability
	// session ID and the call log's key.
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Where to send RTP.
	MediaPort uint32 `protobuf:"varint,2,opt,name=media_port,json=mediaPort,proto3" json:"media_port,omitempty"`
	// The negotiated codec, which may differ from the request only by the
	// gateway rejecting it outright.
	Codec Codec `protobuf:"varint,3,opt,name=codec,proto3,enum=voicedemo.control.v1.Codec" json:"codec,omitempty"`
	// The APM trace this call will be recorded under, so the client can print a
	// link rather than having to search for it.
	TraceId       string `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCallResponse) Reset() {
	*x = StartCallResponse{}
	mi := &file_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCallResponse) ProtoMessage() {}

func (x *StartCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCallResponse.ProtoReflect.Descriptor instead.
func (*StartCallResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *StartCallResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *StartCallResponse) GetMediaPort() uint32 {
	if x != nil {
		return x.MediaPort
	}
	return 0
}

func (x *StartCallResponse) GetCodec() Codec {
	if x != nil {
		return x.Codec
	}
	return Codec_CODEC_UNSPECIFIED
}

func (x *StartCallResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type EndCallRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// What the sender knows it did. The gateway measures the same things
	// independently from the stream; agreement between the two is the evidence
	// that the loss accounting is correct.
	//
	// first_sequence and final_sequence are the load-bearing fields: the
	// sequence numbers of the first and last packets the sender emitted,
	// including any it dropped itself. They are what let the gateway account for
	// loss at the edges of the stream. Both are needed — the blind spot is
	// symmetric.
	FramesOffered     uint64 `protobuf:"varint,2,opt,name=frames_offered,json=framesOffered,proto3" json:"frames_offered,omitempty"`
	PacketsSent       uint64 `protobuf:"varint,3,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsDropped    uint64 `protobuf:"varint,4,opt,name=packets_dropped,json=packetsDropped,proto3" json:"packets_dropped,omitempty"`
	FinalSequence     uint32 `protobuf:"varint,5,opt,name=final_sequence,json=finalSequence,proto3" json:"final_sequence,omitempty"`
	HaveFinalSequence bool   `protobuf:"varint,6,opt,name=have_final_sequence,json=haveFinalSequence,proto3" json:"have_final_sequence,omitempty"`
	FirstSequence     uint32 `protobuf:"varint,8,opt,name=first_sequence,json=firstSequence,proto3" json:"first_sequence,omitempty"`
	HaveFirstSequence bool   `protobuf:"varint,9,opt,name=have_first_sequence,json=haveFirstSequence,proto3" json:"have_first_sequence,omitempty"`
	// Why the call ended, for the call log.
	Reason        string `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCallRequest) Reset() {
	*x = EndCallRequest{}
	mi := &file_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallRequest) ProtoMessage() {}

func (x *EndCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallRequest.ProtoReflect.Descriptor instead.
func (*EndCallRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{2}
}

func (x *EndCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *EndCallRequest) GetFramesOffered() uint64 {
	if x != nil {
		return x.FramesOffered
	}
	return 0
}

func (x *EndCallRequest) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *EndCallRequest) GetPacketsDropped() uint64 {
	if x != nil {
		return x.PacketsDropped
	}
	return 0
}

func (x *EndCallRequest) GetFinalSequence() uint32 {
	if x != nil {
		return x.FinalSequence
	}
	return 0
}

func (x *EndCallRequest) GetHaveFinalSequence() bool {
	if x != nil {
		return x.HaveFinalSequence
	}
	return false
}

func (x *EndCallRequest) GetFirstSequence() uint32 {
	if x != nil {
		return x.FirstSequence
	}
	return 0
}

func (x *EndCallRequest) GetHaveFirstSequence() bool {
	if x != nil {
		return x.HaveFirstSequence
	}
	return false
}

func (x *EndCallRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EndCallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The gateway's independent view, so the client can print a reconciliation
	// and a demo can show the two agreeing.
	PacketsReceived uint64  `protobuf:"varint,1,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	PacketsExpected uint64  `protobuf:"varint,2,opt,name=packets_expected,json=packetsExpected,proto3" json:"packets_expected,omitempty"`
	PacketsLost     uint64  `protobuf:"varint,3,opt,name=packets_lost,json=packetsLost,proto3" json:"packets_lost,omitempty"`
	LossPct         float64 `protobuf:"fixed64,4,opt,name=loss_pct,json=lossPct,proto3" json:"loss_pct,omitempty"`
	JitterMs        float64 `protobuf:"fixed64,5,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"`
	Mos             float64 `protobuf:"fixed64,6,opt,name=mos,proto3" json:"mos,omitempty"`
	// What the jitter buffer and the AI pipeline made of it.
	FramesConcealed uint64   `protobuf:"varint,7,opt,name=frames_concealed,json=framesConcealed,proto3" json:"frames_concealed,omitempty"`
	ConcealPct      float64  `protobuf:"fixed64,8,opt,name=conceal_pct,json=concealPct,proto3" json:"conceal_pct,omitempty"`
	Turns           uint32   `protobuf:"varint,9,opt,name=turns,proto3" json:"turns,omitempty"`
	ToolCalls       uint32   `protobuf:"varint,10,opt,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Transcripts     []string `protobuf:"bytes,11,rep,name=transcripts,proto3" json:"transcripts,omitempty"`
	Replies         []string `protobuf:"bytes,12,rep,name=replies,proto3" json:"replies,omitempty"`
	TraceId         string   `protobuf:"bytes,13,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EndCallResponse) Reset() {
	*x = EndCallResponse{}
	mi := &file_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallResponse) ProtoMessage() {}

func (x *EndCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallResponse.ProtoReflect.Descriptor instead.
func (*EndCallResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{3}
}

func (x *EndCallResponse) GetPacketsReceived() uint64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *EndCallResponse) GetPacketsExpected() uint64 {
	if x != nil {
		return x.PacketsExpected
	}
	return 0
}

func (x *EndCallResponse) GetPacketsLost() uint64 {
	if x != nil {
		return x.PacketsLost
	}
	return 0
}

func (x *EndCallResponse) GetLossPct() float64 {
	if x != nil {
		return x.LossPct
	}
	return 0
}

func (x *EndCallResponse) GetJitterMs() float64 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

func (x *EndCallResponse) GetMos() float64 {
	if x != nil {
		return x.Mos
	}
	return 0
}

func (x *EndCallResponse) GetFramesConcealed() uint64 {
	if x != nil {
		return x.FramesConcealed
	}
	return 0
}

func (x *EndCallResponse) GetConcealPct() float64 {
	if x != nil {
		return x.ConcealPct
	}
	return 0
}

func (x *EndCallResponse) GetTurns() uint32 {
	if x != nil {
		return x.Turns
	}
	return 0
}

func (x *EndCallResponse) GetToolCalls() uint32 {
	if x != nil {
		return x.ToolCalls
	}
	return 0
}

func (x *EndCallResponse) GetTranscripts() []string {
	if x != nil {
		return x.Transcripts
	}
	return nil
}

func (x *EndCallResponse) GetReplies() []string {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *EndCallResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_proto_control_proto protoreflect.FileDescriptor

const file_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x13proto/control.proto\x12\x14voicedemo.control.v1\"\xe2\x01\n" +
	"\x10StartCallRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x121\n" +
	"\x05codec\x18\x03 \x01(\x0e2\x1b.voicedemo.control.v1.CodecR\x05codec\x12\x12\n" +
	"\x04ssrc\x18\x04 \x01(\rR\x04ssrc\x12\x1f\n" +
	"\vreturn_port\x18\x05 \x01(\rR\n" +
	"returnPort\x12'\n" +
	"\x0fnetwork_profile\x18\x06 \x01(\tR\x0enetworkProfile\x12\x19\n" +
	"\bptime_ms\x18\a \x01(\rR\aptimeMs\"\x99\x01\n" +
	"\x11StartCallResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1d\n" +
	"\n" +
	"media_port\x18\x02 \x01(\rR\tmediaPort\x121\n" +
	"\x05codec\x18\x03 \x01(\x0e2\x1b.voicedemo.control.v1.CodecR\x05codec\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\"\xe2\x02\n" +
	"\x0eEndCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12%\n" +
	"\x0eframes_offered\x18\x02 \x01(\x04R\rframesOffered\x12!\n" +
	"\fpackets_sent\x18\x03 \x01(\x04R\vpacketsSent\x12'\n" +
	"\x0fpackets_dropped\x18\x04 \x01(\x04R\x0epacketsDropped\x12%\n" +
	"\x0efinal_sequence\x18\x05 \x01(\rR\rfinalSequence\x12.\n" +
	"\x13have_final_sequence\x18\x06 \x01(\bR\x11haveFinalSequence\x12%\n" +
	"\x0efirst_sequence\x18\b \x01(\rR\rfirstSequence\x12.\n" +
	"\x13have_first_sequence\x18\t \x01(\bR\x11haveFirstSequence\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\"\xac\x03\n" +
	"\x0fEndCallResponse\x12)\n" +
	"\x10packets_received\x18\x01 \x01(\x04R\x0fpacketsReceived\x12)\n" +
	"\x10packets_expected\x18\x02 \x01(\x04R\x0fpacketsExpected\x12!\n" +
	"\fpackets_lost\x18\x03 \x01(\x04R\vpacketsLost\x12\x19\n" +
	"\bloss_pct\x18\x04 \x01(\x01R\alossPct\x12\x1b\n" +
	"\tjitter_ms\x18\x05 \x01(\x01R\bjitterMs\x12\x10\n" +
	"\x03mos\x18\x06 \x01(\x01R\x03mos\x12)\n" +
	"\x10frames_concealed\x18\a \x01(\x04R\x0fframesConcealed\x12\x1f\n" +
	"\vconceal_pct\x18\b \x01(\x01R\n" +
	"concealPct\x12\x14\n" +
	"\x05turns\x18\t \x01(\rR\x05turns\x12\x1d\n" +
	"\n" +
	"tool_calls\x18\n" +
	" \x01(\rR\ttoolCalls\x12 \n" +
	"\vtranscripts\x18\v \x03(\tR\vtranscripts\x12\x18\n" +
	"\areplies\x18\f \x03(\tR\areplies\x12\x19\n" +
	"\btrace_id\x18\r \x01(\tR\atraceId*>\n" +
	"\x05Codec\x12\x15\n" +
	"\x11CODEC_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"CODEC_PCMU\x10\x01\x12\x0e\n" +
	"\n" +
	"CODEC_PCMA\x10\x022\xc4\x01\n" +
	"\fControlPlane\x12\\\n" +
	"\tStartCall\x12&.voicedemo.control.v1.StartCallRequest\x1a'.voicedemo.control.v1.StartCallResponse\x12V\n" +
	"\aEndCall\x12$.voicedemo.control.v1.EndCallRequest\x1a%.voicedemo.control.v1.EndCallResponseB;Z9github.com/mharner33/voice-demo/proto/controlpb;controlpbb\x06proto3"

var (
	file_proto_control_proto_rawDescOnce sync.Once
	file_proto_control_proto_rawDescData []byte
)

func file_proto_control_proto_rawDescGZIP() []byte {
	file_proto_control_proto_rawDescOnce.Do(func() {
		file_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)))
	})
	return file_proto_control_proto_rawDescData
}

var file_proto_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_control_proto_goTypes = []any{
	(Codec)(0),                // 0: voicedemo.control.v1.Codec
	(*StartCallRequest)(nil),  // 1: voicedemo.control.v1.StartCallRequest
	(*StartCallResponse)(nil), // 2: voicedemo.control.v1.StartCallResponse
	(*EndCallRequest)(nil),    // 3: voicedemo.control.v1.EndCallRequest
	(*EndCallResponse)(nil),   // 4: voicedemo.control.v1.EndCallResponse
}
var file_proto_control_proto_depIdxs = []int32{
	0, // 0: voicedemo.control.v1.StartCallRequest.codec:type_name -> voicedemo.control.v1.Codec
	0, // 1: voicedemo.control.v1.StartCallResponse.codec:type_name -> voicedemo.control.v1.Codec
	1, // 2: voicedemo.control.v1.ControlPlane.StartCall:input_type -> voicedemo.control.v1.StartCallRequest
	3, // 3: voicedemo.control.v1.ControlPlane.EndCall:input_type -> voicedemo.control.v1.EndCallRequest
	2, // 4: voicedemo.control.v1.ControlPlane.StartCall:output_type -> voicedemo.control.v1.StartCallResponse
	4, // 5: voicedemo.control.v1.ControlPlane.EndCall:output_type -> voicedemo.control.v1.EndCallResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_control_proto_init() }
func file_proto_control_proto_init() {
	if File_proto_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_proto_goTypes,
		DependencyIndexes: file_proto_control_proto_depIdxs,
		EnumInfos:         file_proto_control_proto_enumTypes,
		MessageInfos:      file_proto_control_proto_msgTypes,
	}.Build()
	File_proto_control_proto = out.File
	file_proto_control_proto_goTypes = nil
	file_proto_control_proto_depIdxs = nil
}
