// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: proto/control.proto

// The control plane mirrors SIP's INVITE/BYE semantics without a SIP stack.
// StartCall negotiates the media parameters and returns a call ID and the port
// to send RTP to; EndCall tears the call down and exchanges each side's view of
// what happened.
//
// It exists because four things are impossible to get right from the media
// stream alone:
//
//  1. Packet loss at the edges of a stream. A receiver reconstructs loss from
//     gaps between sequence numbers that arrived, so it cannot detect loss at
//     either end: nothing later reveals a trailing gap, and nothing earlier
//     anchors a leading one — a receiver whose first packet was dropped simply
//     starts counting one packet in. EndCall carries both ends of the range
//     the sender emitted, which closes the blind spot. Real endpoints learn
//     the same range from RTCP.
//
//  2. Knowing when a call ended. Without a teardown message the gateway has to
//     infer the end from silence, which means it keeps filling playout slots
//     with concealment for as long as its hangover window lasts, inflating the
//     conceal rate of every call.
//
//  3. The return media path. The gateway synthesizes audio but has nowhere to
//     send it until the caller says where to listen.
//
//  4. The client's network impairment profile. Nothing in an RTP stream says
//     how it was degraded, so the gateway cannot otherwise label a call with
//     the conditions it was sent under.

package controlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_StartCall_FullMethodName = "/voicedemo.control.v1.ControlPlane/StartCall"
	ControlPlane_EndCall_FullMethodName   = "/voicedemo.control.v1.ControlPlane/EndCall"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneClient interface {
	// StartCall negotiates media parameters, the SIP INVITE analogue.
	StartCall(ctx context.Context, in *StartCallRequest, opts ...grpc.CallOption) (*StartCallResponse, error)
	// EndCall tears a call down, the SIP BYE analogue, and exchanges each side's
	// accounting so the two can be reconciled.
	EndCall(ctx context.Context, in *EndCallRequest, opts ...grpc.CallOption) (*EndCallResponse, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) StartCall(ctx context.Context, in *StartCallRequest, opts ...grpc.CallOption) (*StartCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartCallResponse)
	err := c.cc.Invoke(ctx, ControlPlane_StartCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) EndCall(ctx context.Context, in *EndCallRequest, opts ...grpc.CallOption) (*EndCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndCallResponse)
	err := c.cc.Invoke(ctx, ControlPlane_EndCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
type ControlPlaneServer interface {
	// StartCall negotiates media parameters, the SIP INVITE analogue.
	StartCall(context.Context, *StartCallRequest) (*StartCallResponse, error)
	// EndCall tears a call down, the SIP BYE analogue, and exchanges each side's
	// accounting so the two can be reconciled.
	EndCall(context.Context, *EndCallRequest) (*EndCallResponse, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) StartCall(context.Context, *StartCallRequest) (*StartCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartCall not implemented")
}
func (UnimplementedControlPlaneServer) EndCall(context.Context, *EndCallRequest) (*EndCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndCall not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_StartCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).StartCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_StartCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).StartCall(ctx, req.(*StartCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_EndCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).EndCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_EndCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).EndCall(ctx, req.(*EndCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voicedemo.control.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartCall",
			Handler:    _ControlPlane_StartCall_Handler,
		},
		{
			MethodName: "EndCall",
			Handler:    _ControlPlane_EndCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/control.proto",
}
